import os

import requests
from dotenv import load_dotenv

load_dotenv()

TOKEN = os.getenv("OPENROUTER_API_TOKEN")
BASE_URL = "https://openrouter.ai/api/v1"

def fetch_and_judge_free_models():
    if not TOKEN:
        print("❌ Error: OPENROUTER_API_TOKEN not found in your .env file.")
        return

    print("📡 Step 1: Fetching live free model catalog from OpenRouter...")
    url = f"{BASE_URL}/models"
    headers = {"Authorization": f"Bearer {TOKEN}"}

    try:
        response = requests.get(url, headers=headers)
        if response.status_code != 200:
            print(f"❌ Failed to fetch. API returned Status {response.status_code}")
            return

        models_data = response.json().get("data", [])
        free_slugs = []

        # Parse out only the 27 models that are completely free to use
        for model in models_data:
            pricing = model.get("pricing", {})
            prompt_cost = float(pricing.get("prompt", 0))
            completion_cost = float(pricing.get("completion", 0))

            if prompt_cost == 0.0 and completion_cost == 0.0:
                free_slugs.append(model.get("id"))

        if not free_slugs:
            print("⚠️ No completely free models found active on this token.")
            return

        print(f"✅ Found {len(free_slugs)} active free models.")
        print("Free Model Slugs:")
        for slug in free_slugs:
            print(f" - {slug}")
        
        print("🧠 Step 2: Consulting the OpenRouter Free Judge to analyze your options...")

        # Construct a specialized prompt tailored to your thesis requirements
        judge_prompt = (
            "You are an academic software engineering advisor. I am working on my undergraduate diploma thesis "
            "focused on generating code for a custom declarative constraint language called 'Goal-DSL' from natural language. "
            "I need an automated verification loop that handles syntax compilation checks and performs self-repair when code fails.\n\n"
            f"Here is the exact list of the {len(free_slugs)} active free model slugs available on my OpenRouter account right now:\n"
            f"{', '.join(free_slugs)}\n\n"
            "Please analyze this specific list and select the TOP 3 best options for my project. Group them precisely into these categories:\n"
            "1. THE STRONGEST CODER: The model from this list best suited for strict, well-formed language generation and syntax parsing layout.\n"
            "2. THE SELF-REPAIR MASTER: The model most capable of analyzing error logs, reasoning through failures, and correcting syntax.\n"
            "3. THE VALUE-FOR-MONEY (VFM) SPEED CHAMPION: A highly efficient, low-latency model ideal for rapid debugging loops.\n\n"
            "For each of the 3 chosen models, provide the EXACT slug from my list and a brief, high-level explanation of its advantage for my thesis work."
        )

        judge_headers = {
            "Authorization": f"Bearer {TOKEN}",
            "HTTP-Referer": "https://github.com/your-username/thesis",
            "X-Title": "Thesis Free Model Selector Tool"
        }
        
        # Using the standard, zero-credit free router as our judge model
        judge_payload = {
            "model": "openrouter/free", 
            "messages": [{"role": "user", "content": judge_prompt}],
            "temperature": 0.3
        }

        judge_response = requests.post(f"{BASE_URL}/chat/completions", headers=judge_headers, json=judge_payload)

        if judge_response.status_code == 200:
            data = judge_response.json()
            analysis = data["choices"][0]["message"]["content"].strip()
            
            # Extract which free model OpenRouter randomly assigned to act as the judge
            assigned_model = data.get("model", "Unknown Free Model")
            
            print("\n======================================================================")
            print(f"🎓 AI ANALYSIS (Generated by active free fallback node: {assigned_model})")
            print("======================================================================")
            print(analysis)
            print("======================================================================")
        else:
            print(f"❌ Judge assignment failed with status {judge_response.status_code}: {judge_response.text}")

    except (requests.RequestException, ValueError, KeyError, TypeError) as e:
        print(f"❌ An error occurred during execution: {e!s}")

if __name__ == "__main__":
    fetch_and_judge_free_models()